spring:
  web:
    resources:
      static-locations: classpath:/static/
  data:
    mongodb:
      uri: ${MONGO_URI}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  messages:
    basename: messages
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 8080